### ISSUE TITLE
Changing of Destination while the TARDIS is in Vortex

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#230]
The Rewrite has another behavior than the legacy if you want to Teleport it with the Sonic.

For remaking, Set the legacy to long flight enabled and Link it. Now you choose 2 Positions. I'll Name them A and B.
Without having a Position selected, press R while you aim at Position A (AimPosTeleport) Because you have set to to long flight, the TARDIS is in the vortex now.

Now, if you WOULD press R again, the TARDIS will appear at A

But we want to do something different. When the TARDIS is in the vortex, Hold Sonic at Position B to set the destination. The old Position was at A. If you press R now to let it Materialien, it should appear on B.
The Rewrite will still appear on A.

The changing of Destination while the TARDIS is in vortex is very important for me.

**Comment by MattJeanes** [comment]
Fixed

**Comment by Noname12345GER** [comment]
Im not sure if i am missing an update, but this still doesnt work for me;

TARDIS Rewrite, 
Official legacy skin provided with original addon.

What i did and what i expected;

Pressed R with no selected destinations
(TARDIS vent into Vortex)
Noclipped to the other end of the map
(Marked spot on Map with Leftclick)
Pressed R to make it reappear
(TARDIS reappeared where i pressed R as AimPos Teleport, expected to arrive on left-click-spot)

**Comment by MattJeanes** [comment]
Did it say in chat 'set tardis destination' or something? Sounds like you may just be missing an update

**Comment by Noname12345GER** [comment]
Well it doesn't want to Auto Update. In an Changelog you said you fixed #230.

**Comment by MattJeanes** [comment]
Yeah, I did. Make sure both rewrite and Sonic are up to date.
