### ISSUE TITLE
In vortex, props, entities and bullets can still go through the portal

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#447]
Found by Blazifall, see Discord for details

**Comment by francodml** [comment]
Can confirm traces still go through as well. Is the custom trace function checking if the portal can actually teleport stuff?

**Comment by MattJeanes** [comment]
Need to hook into the interior ShouldTracePortal hook and return false when in the vortex to fix this

**Comment by MattJeanes** [comment]
* And specifically when the portal == self.portals.interior or it will block other interior portals from working properly. Check existing usage for an example

**Comment by MattJeanes** [comment]
Fixed

**Comment by parar020100** [comment]
It seems like the problem isn't fixed yet. Props can still go through the portal, tested by Blazi
Things can still go in from the outside if the door is open
If put into the portal from the inside, they don't go through the portal, but don't dissapear either - they just stay behind the interior door.
I think that things should either dissapear when put into the vortex or collide with the door like the player does. They definetely shouldn't remain outside the door of interior.
